
export default [
    { label: "By Default", value: "power1-out" },
    { label: "Power 1 in", value: "power1-in" },
    { label: "Power 1 inOut", value: "power1-inOut" },
    { label: "Power 2 in", value: "power2-in" },
    { label: "Power 2 out", value: "power2-out" },
    { label: "Power 2 inOut", value: "power2-inOut" },
    { label: "Power 3 in", value: "power3-in" },
    { label: "Power 3 out", value: "power3-out" },
    { label: "Power 3 inOut", value: "power3-inOut" },
    { label: "Power 4 in", value: "power4-in" },
    { label: "Power 4 out", value: "power4-out" },
    { label: "Power 4 inOut", value: "power4-inOut" },
    { label: "Linear", value: "none" },
    { label: "Back in", value: "back-in" },
    { label: "Back out", value: "back-out" },
    { label: "Back inOut", value: "back-inOut" },
    { label: "elastic in", value: "elastic-in" },
    { label: "elastic out", value: "elastic-out" },
    { label: "elastic inOut", value: "elastic-inOut" },
    { label: "circ in", value: "circ-in" },
    { label: "circ out", value: "circ-out" },
    { label: "circ inOut", value: "circ-inOut" },
    { label: "expo in", value: "expo-in" },
    { label: "expo out", value: "expo-out" },
    { label: "expo inOut", value: "expo-inOut" },
    { label: "Custom", value: "custom" }
];